config/routes.rb
Rails.application.routes.draw do
  # get 'unit_test/index'
  # get 'unit_test/new'
 root :to => 'unit_tests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :unit_tests, except: [:index]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :unit_tests
	has_many :tests, through: :unit_tests
end

app/models/test.rb
class Test < ApplicationRecord
	has_many :unit_tests
	has_many :students, through: :unit_tests
end

app/models/unit_test.rb
class UnitTest < ApplicationRecord
  belongs_to :student
  belongs_to :test
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/unit_tests_controller.rb
class UnitTestsController < ApplicationController
   def index
   end

   def new
   	@students = Student.all
   	@tests = Test.all
   	@unit_test = UnitTest.new
   end

   def create
   	 @test = Test.find_by(subject: "#{params["unit_test"]["test_id"]}")
     student = []
     student_count= 0
     while student_count < Student.all.count
       @student = Student.find_by(id: params["student_id_#{student_count+1}"])
       UnitTest.create!(test_id: @test.id, student_id: @student.id, mark: "#{params["unit_test"].values[student_count+1]}")
      student_count = student_count + 1
     end 
     redirect_to root_path
   end

   def index
    @tests = Test.all

   end


  private 
   def permit_params
       params.require(:unit_test).permit(:mark_1,:mark_2,:mark_3,:test_id)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/unit_test_helper.rb
module UnitTestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentDatabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/unit_tests/index.html.erb
<h2>Marks for students in various tests are</h2>
<p>Create New <%=link_to"Students Marks",new_unit_test_path %> </p> 
<%if  UnitTest.first.present? %>
 <% @tests.each do |test| %>
    <p>Marks for the students for the test <%=test.subject%> </p>
    <ul>
	  <% test.unit_tests.each do |unit_test| %>
	    <li><%= unit_test.student.name %> | <%=unit_test.mark%></li>
	  <%end%>
    </ul>
 <%end%>
<%end%>

app/views/unit_tests/new.html.erb
<%= form_for @unit_test, :locals => {:controller => 'unit_test', :action => 'create'} do |form| %>
   <p> select subject to enter marks for respective tests out of 10 </p>
  
   <%= form.collection_select :test_id, @tests,:subject,:subject%>
   <p> Please enter marks against students name </p>
 <% @students.each_with_index do |student,index| %>

  
   <p id=<%="student_#{index+1}"%>>
    <%= student.name %> |

   <%= form.label :mark %>
    <input type="text" name="unit_test[mark_<%=index+1%>]" id="unit_test_mark_<%=index+1%>">
    <%= hidden_field_tag "student_id_#{index+1}", student.id %>
  
  </p>
 <%end%>
  <p>
    <%= form.submit "submit", :id=>"submit" %>
  </p>
<% end %>